services:
	ffb.instancemanager:
		class:        Flowcode\FinancialBundle\Service\InstanceManagerInterface
		arguments: ["@doctrine.orm.entity_manager"]
	ffb.transaction:
		class:        Flowcode\FinancialBundle\Service\TransactionService
		arguments: ["@ffb.instancemanager"]