Flowcode\FinancialBundle\Entity\Core\Account:
    type: mappedSuperclass
    repositoryClass: Gedmo\Tree\Entity\Repository\NestedTreeRepository
    gedmo:
      tree:
        type: nested
    id:
      id:
        type: integer
        generator:
          strategy: AUTO
    fields:
        code:
            type: string
            length: 255
            nullable: true
        name:
            type: string
            length: 255
        type:
            type: integer
        subType:
            type: integer
            nullable: true
        editable:
            type: boolean
        lft:
          type: integer
          gedmo:
            - treeLeft
        rgt:
          type: integer
          gedmo:
            - treeRight
        lvl:
          type: integer
          gedmo:
            - treeLevel
    manyToOne:
        root:
          targetEntity: Flowcode\FinancialBundle\Entity\Core\Account
          joinColumn:
            name: tree_root
            referencedColumnName: id
            onDelete: CASCADE
          gedmo:
            - treeRoot
        parent:
          targetEntity: Flowcode\FinancialBundle\Entity\Core\Account
          inversedBy: children
          joinColumn:
            name: parent_id
            referencedColumnName: id
            onDelete: CASCADE
          gedmo:
            - treeParent
# No se puede agergar en el abstract
#        oneToMany:
#        children:
#          targetEntity: Flowcode\FinancialBundle\Entity\Core\Account
#          mappedBy: parent
#          orderBy:
#            lft: ASC
    lifecycleCallbacks: {  }
