Flowcode\FinancialBundle\Entity\Core\Account:
    type: mappedSuperclass
    repositoryClass: Gedmo\Tree\Entity\Repository\NestedTreeRepository
    gedmo:
      tree:
        type: nested
    id:
      id:
        type: integer
        generator:
          strategy: AUTO
    fields:
        code:
            type: string
            length: 255
            nullable: true
        name:
            type: string
            length: 255
        type:
            type: integer
        subtype:
            type: string
            length: 255
            nullable: true
        editable:
            type: boolean
        lft:
          type: integer
          gedmo:
            - treeLeft
        rgt:
          type: integer
          gedmo:
            - treeRight
        lvl:
          type: integer
          gedmo:
            - treeLevel
        balance:
            type: float
    manyToOne:
        currency:
            targetEntity: Flowcode\FinancialBundle\Model\Currency\CurrencyInterface
            joinColumn:
                name: currency
                referencedColumnName: id
        root:
            targetEntity: Flowcode\FinancialBundle\Model\Core\AccountInterface
            joinColumn:
              name: tree_root
              referencedColumnName: id
              onDelete: CASCADE
            gedmo:
              - treeRoot
        parent:
            targetEntity: Flowcode\FinancialBundle\Model\Core\AccountInterface
            inversedBy: children
            joinColumn:
              name: parent_id
              referencedColumnName: id
              onDelete: CASCADE
            gedmo:
              - treeParent
# No se puede agergar en el abstract
#        oneToMany:
#        children:
#          targetEntity: Flowcode\FinancialBundle\Model\Core\AccountInterface
#          mappedBy: parent
#          orderBy:
#            lft: ASC
    lifecycleCallbacks: {  }
