Flowcode\FinancialBundle\Entity\Core\Account:
    type: mappedSuperclass

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        code:
            type: string
            length: 255
            nullable: true
        name:
            type: string
            length: 255
        type:
            type: integer
        subType:
            type: integer
        editable:
            type: boolean


    lifecycleCallbacks: {  }
