Flowcode\FinancialBundle\Entity\Core\Transaction:
    type: mappedSuperclass

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        description:
            type: string
            length: 255
            nullable: true
        date:
            type: datetime



    lifecycleCallbacks: {  }
