Flowcode\FinancialBundle\Entity\Currency\Currency:
    type: mappedSuperclass

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
