Flowcode\FinancialBundle\Entity\Document\DocumentItem:
    type: mappedSuperclass

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        description:
            type: string
            length: 255
            nullable: true
        units:
            type: integer
            nullable: true
        unitPrice:
            type: float
            nullable: true
        tax:
            type: float
            nullable: true
        total:
            type: float
    manyToOne:
        document:
            targetEntity: Flowcode\FinancialBundle\Model\Document\DocumentInterface
            inversedBy: documentItems
            joinColumn:
                name: document_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
