Flowcode\FinancialBundle\Entity\Document\DocumentItemTax:
    type: mappedSuperclass

    fields:
        rate:
            type: float
        amount:
            type: float
    lifecycleCallbacks: {  }
