Flowcode\FinancialBundle\Entity\Document\Document:
    type: mappedSuperclass

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        code:
            type: string
            length: 255
            nullable: true
        subType:
            type: string
            length: 255
            nullable: true
        date:
            type: datetime
        balance:
            type: float
            nullable: true
        dueDate:
            type: datetime
            nullable: true
        total:
            type: float
        totalPayed:
            type: float
            nullable: true
    manyToOne:
        category:
            targetEntity: Flowcode\FinancialBundle\Model\Document\DocumentCategoryInterface
            joinColumn:
                name: document_type_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
