Flowcode\FinancialBundle\Entity\Document\DocumentItem:
    type: mappedSuperclass

    fields:
        description:
            type: string
            length: 255
            nullable: true
        units:
            type: integer
            nullable: true
        unitPrice:
            type: float
            nullable: true
        total:
            type: float
    lifecycleCallbacks: {  }
