Flowcode\FinancialBundle\Entity\Document\DocumentCategory:
    type: mappedSuperclass

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        name:
            type: string
            length: 255
        code:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
