Flowcode\FinancialBundle\Model\Document\Document:
    type: mappedSuperclass

    fields:
        code:
            type: string
            length: 255
            nullable: true
        subType:
            type: string
            length: 255
            nullable: true
        date:
            type: datetime
        balance:
            type: float
            nullable: true
        dueDate:
            type: datetime
        total:
            type: float
        totalPayed:
            type: float
            nullable: true
    lifecycleCallbacks: {  }
