Flowcode\FinancialBundle\Entity\Payment\Expense:

    type: mappedSuperclass

    id:
        id:
            type: integer
            generator: { strategy: AUTO }


    fields:
        name:
            type: string
            length: 255

    lifecycleCallbacks: {  }
