Flowcode\FinancialBundle\Entity\Payment\Expense:

    type: mappedSuperclass

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
    manyToMany:
        accounts:
          targetEntity: Flowcode\FinancialBundle\Model\Core\AccountInterface
          joinTable:
            name: financial_expense_account
            joinColumns:
              expense_id:
                referencedColumnName: id
            inverseJoinColumns:
              account_id:
                referencedColumnName: id
    lifecycleCallbacks: {  }
