Flowcode\FinancialBundle\Entity\Payment\Payment:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        type:
            type: string
            length: 255
        amount:
            type: float
    manyToOne:
        method:
            targetEntity: Flowcode\FinancialBundle\Model\Payment\PaymentMethodInterface
            joinColumn:
                name: payment__id
                referencedColumnName: id
    lifecycleCallbacks: {  }
