Flowcode\FinancialBundle\Entity\Payment\Expense:

    type: mappedSuperclass

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
    manyToOne:
        account:
            targetEntity: Flowcode\FinancialBundle\Model\Core\AccountInterface
            joinColumn:
                name: account_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
