Flowcode\FinancialBundle\Model\Payment\Payment:
    type: mappedSuperclass

    fields:
        type:
            type: string
            length: 255
        amount:
            type: float
    lifecycleCallbacks: {  }
