Flowcode\FinancialBundle\Entity\Payment\PaymentMethod:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
    manyToMany:
        accounts:
          targetEntity: Flowcode\FinancialBundle\Model\Core\AccountInterface
          joinTable:
            name: financial_payment_method_account
            joinColumns:
              payment_method_id:
                referencedColumnName: id
            inverseJoinColumns:
              account_id:
                referencedColumnName: id
    lifecycleCallbacks: {  }
