Flowcode\FinancialBundle\Entity\Payment\PaymentMethod:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
    oneToOne:
        account:
            targetEntity: Flowcode\FinancialBundle\Model\Core\AccountInterface
            joinColumn:
                name: account_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
