Flowcode\FinancialBundle\Entity\Tax:
    type: mappedSuperclass

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        name:
            type: string
            length: 255
        rate:
            type: float
        forSale:
            type: boolean
        forPurchase:
            type: boolean
        description:
            type: string
            length: 255

    lifecycleCallbacks: {  }
