Flowcode\FinancialBundle\Model\Core\Transaction:
    type: mappedSuperclass

    fields:
        description:
            type: string
            length: 255
            nullable: true
        date:
            type: datetime

    oneToMany:
        journalEntries:
            targetEntity: JournalEntry
            mappedBy: transactions
            cascade: ["persist"]
    lifecycleCallbacks: {  }
